export const USER_DETAIL_CHANGE = "USER_DETAIL_CHANGE";
export const CHAT_LIST_CHANGE = "CHAT_LIST_CHANGE";
export const NEW_MSG_CHANGE = "NEW_MSG_CHANGE";
export const NEW_MESSAGE_CHATLIST_CHANGE = "NEW_MESSAGE_CHATLIST_CHANGE";
export const CAMERA_DATA_CHANGE = "CAMERA_DATA_CHANGE";
export const REFRESH_CHECK_AUTH = "REFRESH_CHECK_AUTH";
